version: '3.8'
services:
  # server
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}

      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNC=${DB_SYNC}
      - DB_DROP=${DB_DROP}

      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TTL=${REDIS_TTL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - redis
      - postgres
    restart: always
    networks:
      - intra-flow

  # redis
  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass "" # 비밀번호 없음
    networks:
      - intra-flow

  # postgres
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - intra-flow

networks:
  intra-flow:
    driver: bridge

volumes:
  pg_data: